inherit_gem:
  # rubocop-config-umbrellio: lib/rubocop.yml
  # OR
  rubocop-config-umbrellio: lib/rubocop.rails.yml

Rails:
  Enabled: true

  Rails/SaveBang:
  Enabled: false

AllCops:
  TargetRubyVersion: 2.5.3
  Exclude:
    - 'bin/**/*'
    - 'vendor/**/*'
    - 'tmp/**/*'
    - 'spec/**/*'
    - 'test/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'test.rb'
